### ISSUE TITLE
inference with photons

### ISSUE THREAD

**Issue by Shikamaru5** [leptonai/leptonai#107]
So on twitter the Lepton AI account specifies that on Llama your optimized runtime runs up to 90 times faster than the transformer baselines. Is this only something that is implemented in your playground or is this something done through the photons? It states that the "magic" is done underneath but I haven't found anything in your documentation on the website talking about this. Or is it that it's expected the developers will use vLLM for inference optimization. If that's the case why would we need to use the container when we could simply use vLLM at its source? It also may be the case that those optimizations are only coming from the cloud based part of Lepton, which if that's the case it seems a little disingenuous not to state that.

**Comment by Yangqing** [comment]
Thanks for the comments - yes, we agree that currently the inference optimization of various LLMs is a moving target. There are quite a bit of things that are tightly integrated with other infra pieces, and as a result is not that easily open sourceable - we are in the process of contributing such things back, either via our own open source runtime, or via direct contribution into  frameworks like vLLM.

Speaking of vLLM - we are good friends with the vLLM team and we keep an honest and direct communication. The challenge with many people using vLLM today is the need to manage infrastructure - remember, vLLM is a library and you'll need to manage machines and drivers yourself. We help eliminating these "boring but essential" pieces. In fact this is quite welcomed by the vLLM team as they also tweeted about the ease of use.

The choice of inference engine is always a tricky issue as every engine is different. For example, our in house implementation don't take any random LLM model. So does vLLM. So does TGI. That's why we take an open approach by integrating popular frameworks. For example, to run a model, you can choose `hf:model_name` or `vllm:model_name` - such flexibility is actually beneficial to the community we believe.

I respectfully disagree about the "disingenuous" comment - we clearly stated that we are in the process of sharing these, and the cloud service is readily available. In fact, what I believe is that hardware vendors will eventually catch up and provide good abstractions, like NVidia did in the last 10 years with cudnn, tensorrt, triton, fasttransformer, etc. (We worked closely with NVidia on the cudnn work in 2014).

Respectfully closing this issue but feel free to follow up with further discussions.
