### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'leptonai.api.workspace'

### ISSUE THREAD

**Issue by Phil-U-U** [leptonai/leptonai#481]
workspace relevant issue:
from leptonai.api.workspace import WorkspaceInfoLocalRecord
ModuleNotFoundError: No module named 'leptonai.api.workspace'

**To Reproduce**
from leptonai.api.workspace import WorkspaceInfoLocalRecord

**Expected behavior**
Installed leptonai in the docker and worked well for the last iteration, now suddenly incurred the above issue

**Environment (please complete the following information):**
 - OS: linux
 - Python version: 3.10
 - LeptonAI library version: [obtain this via `lep --version`]

**Comment by xlu451** [comment]
It looks like you've encountered an issue with the module leptonai.api.workspace because the old version of the API has been moved to api.v0.

To quickly fix this issue, you could try running:

``` pip install leptonai==0.21.3 ```

However, this is not recommended.

The better solution is to update your import statement as follows:

```python from leptonai.api.v0.workspace import WorkspaceInfoLocalRecord ```

Additionally, we have released a new SDK, and the older version will soon be deprecated. We strongly recommend transitioning to the latest api.v1 SDK to ensure compatibility and take advantage of the latest features and improvements.

If you have any questions or need further assistance, please feel free to reach out.

**Comment by Phil-U-U** [comment]
@xlu451 @bddppq Thank you both for the reply in a timely manner. That's exactly what I was meant. For the up to date solution, I bet the following is the one: 
from leptonai.api.v1.workspace import WorkspaceInfoLocalRecord

**Comment by Phil-U-U** [comment]
No, from leptonai.api.v1.workspace import WorkspaceInfoLocalRecord does not work for v1. I have a temporary solution for myself. But I don't think I use the api.v1 SDK properly as I cannot find the equivalent one for the previous WorkspaceInfoLocalRecord.get_current_workspace_token() which return the token. I put the information here in case other users encounter similar situation while leaving you guys for the rest of it. Thanks again!

**Comment by Yangqing** [comment]
Thanks for the feedback. Yeah, the current new style api provides better format checking, but also differs from earlier usage. To get the WorkspaceInfoLocalRecord equivalent, you can do the following:

```
from leptonai.api.v1.client import APIClient
c = APIClient()
# Gets the token
c.token()
```

You can also do things like
```
# Lists all deployments
c.deployment.list_all()
```

Hope this helps!

**Comment by Phil-U-U** [comment]
There we go! api.v1 has the client. That's what I was hoping for subconsciously.  Thank you @Yangqing That definitely helps!
